version: '2'
services:
  cached: true
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
     - mongo
  mongo:
    cached: true
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"
